# Generated by Django 3.2.9 on 2021-11-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_alter_gallery_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Trainer', 'verbose_name_plural': 'Trainers'},
        ),
    ]
