# Generated by Django 3.2.9 on 2021-11-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_auto_20211112_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
