# Generated by Django 3.2.9 on 2021-11-13 13:59

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_auto_20211112_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
