# Generated by Django 3.2.9 on 2021-11-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0013_auto_20211118_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
