# Generated by Django 3.2.9 on 2021-11-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0014_auto_20211118_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
