# Generated by Django 3.2.9 on 2021-11-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0015_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(),
        ),
    ]
