# Generated by Django 3.2.9 on 2021-11-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0018_remove_profile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
