# Generated by Django 3.2.9 on 2021-11-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0019_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
