# Generated by Django 3.2.9 on 2021-11-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0023_auto_20211118_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
