# Generated by Django 3.2.9 on 2021-11-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0025_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
