# Generated by Django 3.2.9 on 2021-11-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0027_auto_20211118_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
