# Generated by Django 3.2.9 on 2021-11-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0030_auto_20211119_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='dislike',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='like',
            new_name='likes',
        ),
    ]
