# Generated by Django 3.2.9 on 2021-11-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0036_auto_20211120_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_text',
        ),
    ]
