# Generated by Django 3.2.9 on 2021-11-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0037_rename_comment_comment_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='commentxt',
        ),
    ]
