# Generated by Django 3.2.9 on 2021-11-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0038_rename_comment_text_comment_commentxt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentxt',
            new_name='comment',
        ),
    ]
