# Generated by Django 3.2.9 on 2021-11-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0040_comment_dislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='Comments',
        ),
    ]
