# Generated by Django 3.2.9 on 2021-11-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0041_rename_comment_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
