# Generated by Django 3.2.9 on 2021-11-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0043_rename_comments_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
